replicacount: 1

Deployments:
  app_name: springboot
  app_env: spring-config
  db_name: spring-db
  app_port: 8080
  db_port: 3306
  app_url: 760496128264.dkr.ecr.ap-south-1.amazonaws.com/chatapp:springboot
  vol_name: mysqldb
  app_replicas: 1
  db_replicas: 1
  vol_claim_req_storage: 5Gi

Service:
  app_name: springboot
  db_name: spring-db
  app_target_port: 8080
  app_svc: 80
  db_svc: 3306

Credential:
  db_user: mysql
  db_password: admin123
