apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.Deployments.app_env }}
  labels:
    app: {{ .Values.Deployments.db_name }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.Credential.db_password }}
  MYSQL_DATABASE: mysql
  MYSQL_USER: {{ .Values.Credential.db_user }}
  MYSQL_PASSWORD: {{ .Values.Credential.db_password }}


